name: Build Game (Manual GitHub Release)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for the release"
        required: true
        default: "v1.0.0"

permissions:
  contents: write
  pull-requests: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build game package
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Verify build output
        run: |
          if [ ! -f "game.zip" ]; then
            echo "Error: game.zip was not created"
            exit 1
          fi
          echo "Build successful! Created game.zip"
          ls -la game.zip

      - name: Get tag name
        id: get_tag
        run: |
          echo "tag_name=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.tag_name }}
          name: Ping Pong Game ${{ steps.get_tag.outputs.tag_name }} (Manual Release)
          body: |
            ## Ping Pong Game Release ${{ steps.get_tag.outputs.tag_name }} (Manual GitHub Release)

            🎮 **Manual release!** This is a GitHub-only release for manual downloads.

            ### What's included:
            - Complete game files with optimized structure
            - All assets and sounds
            - Phaser 3 runtime (flattened structure)

            ### How to play locally:
            1. Download and extract `ping-pong-game.zip`
            2. Open `index.html` in your web browser
            3. Enjoy the game!

            ### For manual itch.io upload:
            1. Download `ping-pong-game.zip`
            2. Upload to itch.io as HTML project
            3. Set "Kind of project" to "HTML"
            4. Check "This file will be played in the browser"

            **💡 Tip:** For automatic itch.io deployment, use git tags instead: `git tag v1.0.0 && git push origin v1.0.0`

            Built with Phaser 3 🚀
          draft: false
          prerelease: false
          files: game.zip
          generate_release_notes: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: game-build-${{ steps.get_tag.outputs.tag_name }}
          path: game.zip
          retention-days: 30
